enum Events {
   TOUCH = 'TOUCH',
   JUMP = 'JUMP',
   FALL = 'FALL',
   START_GAMEPLAY = 'START_GAMEPLAY',
   RESTART = 'RESTART',
   GAMEPLAY_END = 'GAMEPLAY_END',

   REDIRECT = 'REDIRECT',

   WINDOW_RESIZED_CHANGED = 'WINDOW_RESIZED_CHANGED',
}

export default Events;
